---
title: "extract-recode"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{extract-recode}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(survey.extraction)
library(dplyr)
library(stringr)
library(purrr)
library(haven)
library(rdhs)
```

Load metadata and recoding sheets

```{r load metadata}
ssa_iso3 <- c(
  "BDI", "BEN", "BFA", "CIV", "CMR", "COD", "COG", "GMB", "KEN", "LSO", "MLI", 
  "MOZ", "MWI", "NGA", "SLE", "SWZ", "TCD", "TGO", "ZWE", "AGO", "ETH", "GAB", 
  "GHA", "GIN", "LBR", "NAM", "NER", "RWA", "SEN", "TZA", "UGA", "ZMB"
)

#### Load Recoding Datasets ####
variable_recode = readxl::read_excel(
  system.file('extdata', 'hivdata_survey_datasets.xlsx', package = 'survey.extraction'), sheet = "variable_recode", na = "NA"
)
value_recode = type.convert(readxl::read_excel(
  system.file('extdata', 'hivdata_survey_datasets.xlsx', package = 'survey.extraction'), sheet = "value_recode", na = "NA"
), as.is = TRUE)
```

Find DHS surveys that asked about circumcision

```{r load surveys}

# pull characteristic ID for DHS surveys for circumcision data
characteristic_id <- rdhs::dhs_survey_characteristics() %>%
  filter(grepl("circumcision", SurveyCharacteristicName)) %>% 
  pull(SurveyCharacteristicID)

# Pull surveys with circumcision information
survey_has_circ <- rdhs::dhs_surveys(
  surveyCharacteristicIds = characteristic_id
) %>%
  filter(!SurveyId %in% c("LB2019DHS", "GN2012DHS")) %>%
  mutate(
    survey_id = paste0(
    dhscc_to_iso3(DHS_CountryCode),
    SurveyYear,
    SurveyType
  ))

# Men's recode datasets
mrd <- rdhs::dhs_datasets(fileType = "MR", fileFormat = "FL")


# Get Individual recode datasets w/ circ characteristic and bind in MR datasets
combined_datasets <- dhs_datasets(fileType = "IR", fileFormat = "FL") %>%
  filter(SurveyId %in% dhs_surveys(surveyCharacteristicId = 11)$SurveyId) %>%
  filter(!SurveyId %in% mrd$SurveyId) %>%
  bind_rows(mrd) %>%
  filter(
    dhscc_to_iso3(DHS_CountryCode) %in% ssa_iso3,
    as.integer(SurveyYear) > 1999
  ) %>%
  mutate(
    survey_id = paste0(
      dhscc_to_iso3(DHS_CountryCode), SurveyYear, SurveyType)
  ) %>%
  filter(!survey_id %in% c("LSO2014DHS"))

circ_raw <- get_datasets(combined_datasets, clear_cache = TRUE) %>%
  setNames(combined_datasets$survey_id) %>%
  .[grepl("\\.rds$", .)] %>%
  lapply(readRDS)

```

Extract and recode variables

```{r extract and recode}

file_type <- c(
    "Individual Recode" = "ir", 
    "Men's Recode" = "mr"
  )[combined_datasets$FileType] %>% 
    setNames(combined_datasets$survey_id)
  
circ_extracted <- Map(
  extract_survey_vars,
  df = circ_raw,
  survey_id = names(circ_raw),
  list(variable_recode),
  file_type[names(circ_raw)],
  analysis = "circ"
)

circ_recoded <- Map(
  recode_survey_variables,
  df = circ_extracted,
  survey_id = names(circ_extracted),
  list(value_recode),
  file_type[names(circ_extracted)],
  analysis = "circ"
)
```
